### ISSUE TITLE
Version of Python and TensorFlow

### ISSUE THREAD

**Issue by Guidosalimbeni** [mantasp/barracuda-release#2]
Dear Sir,
I am having some issues to convert a pb model to nn type format. My concern is that I need a specific version of python and tensorFlow. I am currently using python 3.5 and TensorFlow 1.8 but I got an error "data" referenced before ... when trying to use tensorflow to barracuda script. I wonder if it is because I need a specific version of python and tf? I am on Windows
Best regards
ps. trained a MobileNetV2 with 1 added dense layer that I used for transfer learning.

**Comment by rash1994** [comment]
hie Guidosalimbeni,
Did you get the compatibility of version of tf and python ?



Thanks

**Comment by Guidosalimbeni** [comment]
In the end, I changed my plan.
I am still not able to convert Tensorflow model into barracuda NN file format.  But I am able to use the tensorflow model with tensorFlowSharp in Unity. I have python 3.5 TF 1.7.1 and TFsharp 4.0 . 
At one point I will have to look back on how to convert TF model to Barracuda. I posted a question, I think soon I will get an answer.

**Comment by rash1994** [comment]
Thank you for the reply.
I am also searching for the same thing. May be we need to code the
convertor according to our tf model.

Can you please guide me on using TensorflowSharp in unity ?

**Comment by Guidosalimbeni** [comment]
Sorry,
I don't think I am the right person to suggest a solution or guidance. I am still experimenting...beginner,,

**Comment by rash1994** [comment]
Okay.

Thank you.
