### ISSUE TITLE
GroupMemoryBarrierWithGroupSync

### ISSUE THREAD

**Issue by NiirirGomel** [mantasp/barracuda-release#4]
Hi, mantasp.
When I try to run my model on barracuda 2.4 with shaders above 2.2, a GroupMemoryBarrierWithGroupSync error appears on mobile devices. Maybe GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS not counted.

**Comment by mantasp** [comment]
Could you please try version 0.3.0 and see if it improved?
Thanks
