### ISSUE TITLE
Tensorflow_To_Barracuda

### ISSUE THREAD

**Issue by JonasX99** [mantasp/barracuda-release#9]
I get this error google.protobuf.message.DecodeError: Error parsing message. When trying to convert it to Barracuda.

the model is a pb file and i trained the model with [Teachable Machine](https://teachablemachine.withgoogle.com/).

**Comment by mantasp** [comment]
Please report these issues on https://github.com/Unity-Technologies/barracuda-release, this fork is for mirroring purposes only.
